### ISSUE TITLE
Port 9000: The connection was reset

### ISSUE THREAD

**Issue by Fmstrat** [aknaebel/docker-vimbadmin#1]
Hi,

Trying to get this running using the sample `docker-compose.yml`. On a fresh start, I'm getting a "The connection was reset" error when visiting port 9000.

Here's my docker-compose:
```
version: '2'

services:

# ----------- vimbadmin begin ----------- #

  vimbadmin-memcached:
    image: memcached
    container_name: vimbadmin-memcached

  vimbadmin-mariadb:
    image: mariadb
    container_name: vimbadmin-mariadb
    volumes:
      - ./vimbadmin-mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vimbadmin
      - MYSQL_USER=vimbadmin
      - MYSQL_PASSWORD=vimbadmin_password

  vimbadmin:
    image: aknaebel/vimbadmin:latest
    container_name: vimbadmin
    links:
      - vimbadmin-mariadb
      - vimbadmin-memcached
    ports:
      - 9000:9000
    environment:
      - VIMBADMIN_PASSWORD=vimbadmin_password
      - DBHOST=vimbadmin-mariadb
      - MEMCACHE_HOST=vimbadmin-memcached
      - ADMIN_EMAIL=vimbadmin@DOMAIN.com
      - ADMIN_PASSWORD=admin1239
      - SMTP_HOST=mail.DOMAIN.com
      - APPLICATION_ENV=production
      - OPCACHE_MEM_SIZE=128

# ----------- vimbadmin end ----------- #
```

Everything starts up OK, but from an external browser I can't access and internally I get:

```
Looking up localhost first
Looking up localhost:9000
Making HTTP connection to localhost:9000
Sending HTTP request.
HTTP request sent; waiting for response.
Alert!: Unexpected network read error; connection aborted.
Can't Access `http://localhost:9000/'
Alert!: Unable to access document.
```

Any idea? Docker running nginx runs fine externally on 9000 so it's not a firewall issue (used that to test).

**Comment by Fmstrat** [comment]
Doh, realized I needed to use nginx, but it's still having an issue. Here's what I've got now:

docker-compose:
```
version: '2'

networks:
  extnet:
    external: true
  intnet:
    driver: bridge

volumes:
  vimbadminvol:

services:

# ----------- vimbadmin begin ----------- #

  vimbadmin-memcached:
    image: memcached
    container_name: vimbadmin-memcached
    networks:
      - intnet

  vimbadmin-mariadb:
    image: mariadb
    container_name: vimbadmin-mariadb
    volumes:
      - ./vimbadmin-mariadb/data:/var/lib/mysql
    networks:
      - intnet
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vimbadmin
      - MYSQL_USER=vimbadmin
      - MYSQL_PASSWORD=vimbadmin_password

 vimbadmin:
    image: aknaebel/vimbadmin:latest
    container_name: vimbadmin
    links:
      - vimbadmin-mariadb
      - vimbadmin-memcached
    networks:
      - intnet
    volumes:
      - vimbadminvol:/var/www/vimbadmin
    environment:
      - VIMBADMIN_PASSWORD=vimbadmin_password
      - DBHOST=vimbadmin-mariadb
      - MEMCACHE_HOST=vimbadmin-memcached
      - ADMIN_EMAIL=vimbadmin@DOMAIN.com
      - ADMIN_PASSWORD=admin1239
      - SMTP_HOST=mail.DOMAIN.com
      - APPLICATION_ENV=production
      - OPCACHE_MEM_SIZE=128

# ----------- vimbadmin end ----------- #

#----------- nginx begin ----------- #

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - vimbadminvol:/vimbadmin
    environment:
      - VIRTUAL_HOST=HOST.DOMAIN.com
    networks:
      - intnet
      - extnet
    ports:
      - 80:80
      - 443:443
    restart: always

# ----------- nginx end ----------- #
```

nginx.conf:
```
user www-data;

events {
        worker_connections 768;
}

http {
        server {
                listen 80;
                server_name HOST.DOMAIN.com;
                root /vimbadmin/public;
                index index.php;
                location / {
                        try_files $uri $uri/ /index.php?$args;
                }
                location ~ \.php$ {
                        try_files $uri =404;
                        fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        #fastcgi_pass    unix:/var/run/php5-fpm.sock;
                        fastcgi_pass    vimbadmin:9000;
                        fastcgi_index   index.php;
                        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        include         fastcgi_params;
                }
        }

}
```

The volume mounts fine, but I get this error when loading the page:
```
nginx                  | 2017/08/16 14:52:58 [error] 5#5: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: <IP>, server: HOST.DOMAIN.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.18.0.5:9000", host: "HOST.DOMAIN.com:80"
```
